
esphome:
  name: smartdry
  friendly_name: SmartDry
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  local: true
  
esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 90ms
    active: false
  on_ble_manufacturer_data_advertise:
    - manufacturer_id: "01AE"
      then:
        - lambda: |-
            id(raw_sensor).publish_state(format_hex(x));

            if (x.size() >= 4) {
              uint32_t temp = (x[0] + (x[1] << 8) + (x[2] << 16) + (x[3] << 24));
              id(temp_sensor).publish_state((*(float *) &temp));
            }

            if (x.size() >= 8) {
              uint32_t hum = (x[4] + (x[5] << 8) + (x[6] << 16) + (x[7] << 24));
              float humidity = (*(float *) &hum);
              id(hum_sensor).publish_state(humidity);

              float dryness = -1.03 * humidity + 100;
              id(dryness_sensor).publish_state(dryness);
            }

            if (x.size() >= 10) {
              uint16_t shake = x[8] + (x[9] << 8);
              id(shake_sensor).publish_state(shake);
            }

            if (x.size() >= 11) {
              uint8_t batt = x[10];
              float battery_voltage = ((batt + 2847.0) / 1000);
              id(batt_sensor).publish_state(battery_voltage);
            }

            if (x.size() >= 12) {
              uint8_t wake = x[11];
              id(wake_sensor).publish_state(static_cast<int>(wake));
            } else {
              id(wake_sensor).publish_state(0);  // fallback if wake byte is missing
            }


sensor:
  - platform: template
    name: "SmartDry Temperature"
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 4
    id: temp_sensor

  - platform: template
    name: "SmartDry Humidity"
    device_class: humidity
    unit_of_measurement: "%"
    accuracy_decimals: 2
    id: hum_sensor

  - platform: template
    name: "SmartDry Shake"
    id: shake_sensor
    accuracy_decimals: 1

  - platform: template
    name: "SmartDry Battery"
    device_class: voltage
    unit_of_measurement: "V"
    accuracy_decimals: 2
    id: batt_sensor

  - platform: template
    name: "SmartDry Awake"
    id: wake_sensor
    accuracy_decimals: 1

  - platform: template
    name: "SmartDry Dryness"
    unit_of_measurement: "%"
    accuracy_decimals: 2
    id: dryness_sensor

binary_sensor:
  - platform: template
    name: "SmartDry Awake Status"
    id: smartdry_awake_binary
    lambda: |-
      return id(wake_sensor).state > 0;
    device_class: running
    on_press:
      - logger.log: "SmartDry is now Awake"
    on_release:
      - logger.log: "SmartDry is now Asleep"

text_sensor:
  - platform: template
    name: "SmartDry Raw"
    id: raw_sensor

output:
  - platform: ledc
    pin: GPIO2
    id: onboard_led

light:
  - platform: monochromatic
    output: onboard_led
    name: "Running Light"
    restore_mode: ALWAYS_OFF